version: "3.8"
services:
  redis:
    image: redis:latest
    networks: 
      - testNet
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: 
      - /home/ubuntu/docker/docker-compose-angkringanhits/config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgre:
    image: testdb:latest
    networks: 
      - testNet
    environment: 
      POSTGRES_PASSWORD: Karyaanakdesa632
      POSTGRES_USER: angkringanhits
      POSTGRES_DB: Angkringanhits
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backendangkringanhits:latest
    depends_on: 
      postgre:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /home/ubuntu/log:/log
    networks: 
      - testNet
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: safrudin
      POSTGRE_USER: angkringanhits
      POSTGRE_PASSWORD: Karyaanakdesa632
      POSTGRE_DB: Angkringanhits
      POSTGRE_HOST: postgre
      POSTGRE_PORT: 5432
      CLOUDINARY_CLOUD: angkringanhits
      CLOUDINARY_KEY: 133374334785943
      CLOUDINARY_SECRET: Inv8mxM9R0PitK1EW2WoJh8hGvE
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  webservice:
    image: webservice
    depends_on: 
      - backend
    ports: 
      - "80:80"
    networks: 
      - testNet

networks: 
  testNet:
